#MODEL:
model_name: exp48_decoder26
model_type: experimental2
num_classes: 45 # reduced
ignore_value: 65
pretrained_backbone: False

#OPTIM:
epochs: 240
max_epochs: 240
resume: False
lr: 0.05
momentum: 0.9
weight_decay: 0.0001
class_weight: null
bn_weight_decay: False
bn_precise_stats: False
bn_precise_num_samples: 600
lr_scheduler: poly
poly_power: 0.9
warmup_iters: 3000
warmup_factor: 0.1

#TRAIN:
mixed_precision: True
run: 1
RNG_seed: 0
loss_type: cross_entropy
eval_while_train: True
exclude_classes: []

#benchmark
warmup_iter: 10
num_iter: 100
benchmark_loader: True
benchmark_model: True

#dataset
dataset_name: mapillary
dataset_dir: mapillary_dataset
mapillary_reduced: True
batch_size: 8
train_min_size: 400
train_max_size: 1600
train_crop_size: [768,768]
val_input_size: 1024
val_label_size: 1024
aug_mode: baseline
num_workers: 4
class_uniform_pct: 0
train_split: train
val_split: val
max_eval: 10000
validate_train_loader: False
eval_print_every: 1000
train_print_every: 400

#checkpoint
pretrained_path: ''
save_every_k_epochs: 8
save_last_k_epochs: 20
save_dir: checkpoints
log_dir: training_log
save_name: mapillary_exp48_decoder26_240_epochs
